---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "cert-manager-webhook-domeneshop.name" . }}
      release: {{ .Release.Name }}
  ingress:
    - ports:
        - port: 443